/**
 * District → Tehsil mapping for Pakistan.
 * Source: Wikipedia "List of tehsils of Pakistan" (2023 census data).
 * Keys should match district names used in district_coordinates table.
 */

export const DISTRICT_TEHSILS: Record<string, string[]> = {
  // ── Khyber Pakhtunkhwa ──────────────────────────────────────────
  "Bannu": ["Bannu", "Baka Khel", "Domel", "Kakki", "Miryan", "Wazir"],
  "Lakki Marwat": ["Lakki Marwat", "Bettani", "Ghazni Khel", "Sari Naurang"],
  "North Waziristan": ["Miran Shah", "Mir Ali", "Datta Khel", "Dossali", "Gharyum", "Ghulam Khan", "Razmak", "Shewa", "Spinwam"],
  "Dera Ismail Khan": ["Dera Ismail Khan", "Daraban", "Drazanda", "Kulachi", "Paharpur", "Paniala", "Paroa"],
  "South Waziristan": ["Wana", "Birmil", "Shakai", "Toi Khulla", "Ladha", "Makin", "Sararogha", "Sarwakai", "Shaktoi", "Shawal", "Tiarza", "Jandola"],
  "Tank": ["Tank", "Jandola"],
  "Abbottabad": ["Abbottabad", "Havelian", "Lora", "Lower Tanawal"],
  "Bajaur": ["Khar", "Bar Chamarkand", "Barang", "Mamund", "Nawagai", "Salarzai", "Utman Khel"],
  "Battagram": ["Batagram"],
  "Buner": ["Daggar", "Chagharzai", "Gadezai", "Gagra", "Khudu Khel", "Mandanr"],
  "Charsadda": ["Charsadda", "Shabqadar", "Tangi"],
  "Chitral": ["Chitral", "Drosh"],
  "Chitral Lower": ["Chitral", "Drosh"],
  "Chitral Upper": ["Mastuj", "Buni", "Mulkoh", "Torkoh"],
  "Daraban": ["Daraban"],
  "Dir Lower": ["Timergara", "Adenzai", "Balambat", "Khal", "Lal Qilla", "Munda", "Samar Bagh"],
  "Dir Upper": ["Dir", "Barawal", "Kalkot", "Sharingal"],
  "Hangu": ["Hangu", "Tall", "Doaba"],
  "Haripur": ["Haripur", "Ghazi", "Khanpur"],
  "Karak": ["Karak", "Banda Daud Shah", "Takht-e-Nasrati"],
  "Khyber": ["Bara", "Jamrud", "Landi Kotal", "Mula Gori", "Bagh Maidan", "Bazar Zakha Khel", "Fort Salop", "Painda Cheena"],
  "Kohat": ["Kohat", "Dara Adam Khel", "Gumbat", "Lachi"],
  "Kohistan Lower": ["Bankad", "Pattan"],
  "Kohistan Upper": ["Dassu", "Kandia", "Seo", "Harban Basha"],
  "Kolai-Palas": ["Kolai", "Palas"],
  "Kurram": ["Central Kurram", "Lower Kurram", "Upper Kurram"],
  "Malakand": ["Sam Ranizai", "Swat Ranizai", "Thana Baizai"],
  "Mansehra": ["Mansehra", "Baffa Pakhal", "Balakot", "Darband", "Oghi", "Tanawal"],
  "Mardan": ["Mardan", "Garhi Kapura", "Katlang", "Rustam", "Takht Bhai"],
  "Mohmand": ["Halim Zai", "Ambar Utman Khel", "Pindiali", "Pran Ghar", "Safi", "Upper Mohmand", "Yake Ghund"],
  "Nowshera": ["Nowshera", "Jehangira", "Pabbi"],
  "Orakzai": ["Central Orakzai", "Lower Orakzai", "Upper Orakzai", "Ismail Zai"],
  "Peshawar": ["Peshawar City", "Badhber", "Chamkani", "Hassan Khel", "Mathra", "Peshtakhara", "Shah Alam"],
  "Shangla": ["Alpuri", "Bisham", "Chakesar", "Martung", "Puran"],
  "Swabi": ["Swabi", "Lahor", "Razar", "Topi"],
  "Swat": ["Babuzai", "Barikot", "Charbagh", "Kabal", "Behrain", "Khwaza Khela", "Matta"],
  "Torghar": ["Daur Maira", "Judba", "Khander Hassanzai"],
  // Allai District (sometimes listed under KP)
  "Allai": ["Allai"],

  // ── Balochistan ──────────────────────────────────────────────────
  "Awaran": ["Awaran", "Gishkaur", "Jhal Jhao", "Korak Jhao", "Mashkay"],
  "Barkhan": ["Barkhan"],
  "Bolan": ["Dhadar"],
  "Chagai": ["Chagai", "Dalbandin", "Nok Kundi", "Taftan"],
  "Chaman": ["Chaman", "Chaman Saddar"],
  "Dera Bugti": ["Dera Bugti", "Sui", "Baiker", "Phelawagh"],
  "Gwadar": ["Gwadar", "Jiwani", "Ormara", "Pasni"],
  "Harnai": ["Harnai", "Shahrig", "Khost"],
  "Jhal Magsi": ["Jhal Magsi", "Gandakha"],
  "Kachhi": ["Dhadar", "Bhag", "Mach"],
  "Kalat": ["Kalat", "Mangocher", "Gazg", "Johan"],
  "Kech": ["Turbat", "Buleda", "Dasht", "Hoshab", "Tump"],
  "Kharan": ["Kharan", "Sar Kharan", "Tohumullah"],
  "Khuzdar": ["Khuzdar", "Nal", "Wadh", "Zehri"],
  "Kohlu": ["Kohlu", "Kahan", "Maiwand", "Tamboo"],
  "Lasbela": ["Uthal", "Bela", "Lakhra", "Kanraj", "Liari"],
  "Loralai": ["Bori", "Mekhtar"],
  "Mastung": ["Mastung", "Dasht", "Khad Koocha", "Kardigap"],
  "Musakhel": ["Musakhel", "Darug", "Kingri", "Toisar", "Zimri Plaseen"],
  "Nasirabad": ["Dera Murad Jamali", "Tamboo", "Chattar"],
  "Nushki": ["Nushki", "Dak"],
  "Panjgur": ["Panjgur", "Gichk"],
  "Pishin": ["Pishin", "Barshore", "Hurramzai"],
  "Quetta": ["Quetta City", "Quetta Saddar"],
  "Sherani": ["Sherani"],
  "Sibi": ["Sibi", "Kutmandai", "Sangan", "Lehri"],
  "Turbat": ["Turbat", "Buleda", "Dasht", "Hoshab", "Tump"],
  "Washuk": ["Washuk", "Besima", "Mashkel", "Nag", "Shahgori"],
  "Zhob": ["Zhob", "Qamar Din Karez"],
  "Ziarat": ["Ziarat", "Sinjawi"],

  // ── Punjab ───────────────────────────────────────────────────────
  "Attock": ["Attock", "Fateh Jang", "Hassan Abdal", "Hazro", "Jand", "Pindi Gheb"],
  "Bahawalnagar": ["Bahawalnagar", "Chishtian", "Haroonabad", "Minchinabad", "Fort Abbas"],
  "Bahawalpur": ["Bahawalpur City", "Bahawalpur Saddar", "Ahmadpur East", "Hasilpur", "Khairpur Tamewali", "Yazman"],
  "Bhakkar": ["Bhakkar", "Darya Khan", "Kaloorkot", "Mankera"],
  "Chakwal": ["Chakwal", "Choa Saidan Shah", "Kallar Kahar"],
  "Chiniot": ["Chiniot", "Bhowana", "Lalian"],
  "Dera Ghazi Khan": ["Dera Ghazi Khan", "Kot Chutta"],
  "Faisalabad": ["Faisalabad City", "Faisalabad Sadar", "Chak Jhumra", "Jaranwala", "Samundri", "Tandlianwala"],
  "Gujar Khan": ["Gujar Khan"],
  "Gujranwala": ["Gujranwala City", "Gujranwala Saddar", "Kamoke", "Nowshera Virkan", "Wazirabad", "Ali Pur Chatta"],
  "Gujrat": ["Gujrat", "Kharian", "Sarai Alamgir", "Jalalpur Jattan", "Kunjah"],
  "Hafizabad": ["Hafizabad", "Pindi Bhattian"],
  "Jhang": ["Jhang", "Shorkot", "Ahmadpur Sial", "Athara Hazari"],
  "Jhelum": ["Jhelum", "Dina", "Pind Dadan Khan", "Sohawa"],
  "Kasur": ["Kasur", "Chunian", "Kot Radha Kishan", "Pattoki"],
  "Khanewal": ["Khanewal", "Jahanian", "Kabirwala", "Mian Channu"],
  "Khushab": ["Khushab", "Noorpur Thal", "Quaidabad", "Naushera"],
  "Lahore": ["Lahore City", "Lahore Cantonment", "Model Town", "Raiwind", "Shalimar"],
  "Layyah": ["Layyah", "Karor Lal Esan", "Chaubara"],
  "Lodhran": ["Lodhran", "Dunyapur", "Kahror Pacca"],
  "Mianwali": ["Mianwali", "Isakhel", "Piplan"],
  "Multan": ["Multan City", "Multan Saddar", "Jalalpur Pirwala", "Shujabad"],
  "Muzaffargarh": ["Muzaffargarh", "Jatoi", "Alipur"],
  "Nankana Sahib": ["Nankana Sahib", "Sangla Hill", "Shah Kot"],
  "Narowal": ["Narowal", "Shakargarh", "Zafarwal"],
  "Okara": ["Okara", "Depalpur", "Renala Khurd"],
  "Pakpattan": ["Pakpattan", "Arifwala"],
  "Rahim Yar Khan": ["Rahim Yar Khan", "Sadiqabad", "Liaqatpur", "Khanpur Katora"],
  "Rajanpur": ["Rajanpur", "Rojhan"],
  "Rawalpindi": ["Rawalpindi", "Gujar Khan", "Kahuta", "Kallar Syedan", "Taxila"],
  "Sahiwal": ["Sahiwal", "Chichawatni"],
  "Sargodha": ["Sargodha", "Bhalwal", "Bhera", "Kot Momin", "Sahiwal", "Shahpur", "Sillanwali"],
  "Sheikhupura": ["Sheikhupura", "Muridke", "Ferozewala", "Safdarabad", "Sharak Pur"],
  "Sialkot": ["Sialkot", "Daska", "Pasrur", "Sambrial"],
  "Toba Tek Singh": ["Toba Tek Singh", "Gojra", "Kamalia", "Pirmahal"],
  "Vehari": ["Vehari", "Burewala", "Mailsi"],
  "Mandi Bahauddin": ["Mandi Bahauddin", "Malakwal", "Phalia"],

  // ── Sindh ────────────────────────────────────────────────────────
  "Badin": ["Badin", "Matli", "Shaheed Fazil Rahu", "Talhar", "Tando Bago"],
  "Dadu": ["Dadu", "Johi", "Khairpur Nathan Shah", "Mehar"],
  "Ghotki": ["Ghotki", "Daharki", "Mirpur Mathelo", "Ubauro"],
  "Hyderabad": ["Hyderabad City", "Hyderabad", "Latifabad", "Qasimabad"],
  "Jacobabad": ["Jacobabad", "Garhi Khairo", "Thul"],
  "Jamshoro": ["Kotri", "Sehwan", "Manjhand", "Thana Bulla Khan"],
  "Karachi Central": ["Gulberg", "Liaquatabad", "North Nazimabad", "New Karachi"],
  "Karachi East": ["Jamshed", "Gulshan-e-Iqbal", "Ferozabad"],
  "Karachi South": ["Saddar", "Lyari", "Arambagh"],
  "Karachi West": ["Kemari", "SITE", "Baldia", "Orangi"],
  "Kashmore": ["Kashmore", "Kandhkot", "Tangwani"],
  "Khairpur": ["Khairpur", "Gambat", "Kingri", "Kot Diji", "Mehrabpur", "Nara", "Sobhodero", "Thari Mirwah"],
  "Larkana": ["Larkana", "Bakrani", "Dokri", "Ratodero"],
  "Matiari": ["Matiari", "Hala", "Saeedabad"],
  "Mirpur Khas": ["Mirpur Khas", "Digri", "Hussain Bux Mari", "Jhuddo", "Kot Ghulam Muhammad", "Shujabad"],
  "Nawabshah": ["Nawabshah", "Daur", "Sakrand"],
  "Naushahro Feroze": ["Naushahro Feroze", "Bhiria", "Kandiaro", "Moro"],
  "Sanghar": ["Sanghar", "Jam Nawaz Ali", "Khipro", "Sinjhoro", "Shahdadpur", "Tando Adam"],
  "Shikarpur": ["Shikarpur", "Garhi Yasin", "Khanpur", "Lakhi"],
  "Sukkur": ["Sukkur", "Pano Aqil", "Rohri", "Saleh Pat"],
  "Tando Allahyar": ["Tando Allahyar", "Chamber", "Jhando Mari"],
  "Tando Muhammad Khan": ["Tando Muhammad Khan", "Bulri Shah Karim", "Tando Ghulam Hyder"],
  "Tharparkar": ["Mithi", "Chachro", "Dahli", "Diplo", "Islamkot", "Kaloi", "Nagarparkar"],
  "Thatta": ["Thatta", "Ghorabari", "Keti Bunder", "Mirpur Sakro"],
  "Umerkot": ["Umerkot", "Kunri", "Pithoro", "Samaro"],
  "Sujawal": ["Sujawal", "Jati", "Kharo Chan", "Mirpur Bathoro", "Shah Bandar"],

  // ── Azad Kashmir ─────────────────────────────────────────────────
  "Bagh": ["Bagh", "Dhirkot", "Hari Ghel"],
  "Bhimber": ["Bhimber", "Barnala", "Samahni"],
  "Hattian Bala": ["Hattian Bala", "Chinari", "Leepa"],
  "Haveli": ["Haveli", "Mumtaz Abad"],
  "Kotli": ["Kotli", "Khuiratta", "Sehnsa", "Tattapani"],
  "Mirpur": ["Mirpur", "Chakswari", "Dadyal"],
  "Muzaffarabad": ["Muzaffarabad", "Pattika", "Hattian"],
  "Neelum": ["Athmuqam", "Sharda", "Kel", "Dudhnial"],
  "Poonch": ["Rawalakot", "Abbaspur", "Hajira", "Thorar"],
  "Sudhanoti": ["Pallandri", "Baloch", "Trarkhal"],

  // ── Gilgit-Baltistan ─────────────────────────────────────────────
  "Astore": ["Astore"],
  "Diamer": ["Chilas", "Darel", "Tangir"],
  "Ghanche": ["Ghanche", "Mashabrum"],
  "Ghizer": ["Gahkuch", "Ishkoman", "Phander", "Yasin"],
  "Gilgit": ["Gilgit", "Danyore", "Juglot"],
  "Hunza": ["Aliabad", "Gulmit", "Passu"],
  "Kharmang": ["Kharmang"],
  "Nagar": ["Nagar"],
  "Shigar": ["Shigar"],
  "Skardu": ["Skardu", "Roundu", "Shigar"],

  // ── Islamabad ────────────────────────────────────────────────────
  "Islamabad": ["Islamabad"],

  // ── Special entries used in the app ──────────────────────────────
  "Waziristan": ["Miran Shah", "Mir Ali", "Wana", "Razmak", "Ladha", "Datta Khel", "Spinwam", "Sararogha", "Birmil"],
  "Afghan Border": [],
};

/**
 * Get tehsils for a given district name.
 * Returns the list or an empty array if the district is not mapped.
 */
export function getTehsilsForDistrict(district: string | null | undefined): string[] {
  if (!district) return [];
  const trimmed = district.trim();
  return DISTRICT_TEHSILS[trimmed] || [];
}
